### ISSUE TITLE
java.lang.IllegalStateException: java.lang.NoSuchFieldException: defaultGenerator

### ISSUE THREAD

**Issue by auniyal** [Squarespace/jersey2-guice#36]
Looks like `InjectionsUtils` is expecting a field `defaultGenerator` which is no more supported

I get following exception when my container startup and tries to instantiate my listener which extends `JerseyGuiceServletContextListener`
```
Could not instantiate listener com.XXXX.jersey2.bootstrap.JerseyContextListener
java.lang.IllegalStateException: java.lang.NoSuchFieldException: defaultGenerator
	at com.squarespace.jersey2.guice.InjectionsUtils.install(InjectionsUtils.java:77)
	at com.squarespace.jersey2.guice.BootstrapUtils.install(BootstrapUtils.java:128)
	at com.squarespace.jersey2.guice.BootstrapUtils.install(BootstrapUtils.java:117)
	at com.squarespace.jersey2.guice.JerseyGuiceServletContextListener.<init>(JerseyGuiceServletContextListener.java:54)
	at com.XXXX.jersey2.bootstrap.JerseyContextListener.<init>(JerseyContextListener.java:26)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at java.lang.Class.newInstance(Class.java:438)
	at org.mortbay.jetty.webapp.WebXmlConfiguration.newListenerInstance(WebXmlConfiguration.java:650)
	at org.mortbay.jetty.webapp.WebXmlConfiguration.initListener(WebXmlConfiguration.java:631)
	at org.mortbay.jetty.webapp.WebXmlConfiguration.initWebXmlElement(WebXmlConfiguration.java:368)
	at org.mortbay.jetty.plus.webapp.AbstractConfiguration.initWebXmlElement(AbstractConfiguration.java:190)
	at org.mortbay.jetty.webapp.WebXmlConfiguration.initialize(WebXmlConfiguration.java:289)
	at org.mortbay.jetty.plus.webapp.AbstractConfiguration.initialize(AbstractConfiguration.java:133)
```

I am using following build.gradle
```
  compile group: 'org.glassfish.jersey.containers', name: 'jersey-container-servlet', version: '2.+'
  compile group: 'org.glassfish.jersey.media', name: 'jersey-media-json-jackson', version: '2.+'
  compile group: 'com.squarespace.jersey2-guice', name: 'jersey2-guice', version: '0.+'
  provided group: 'javax.servlet', name: 'servlet-api', version: '2.5'
  provided group: 'javax.servlet', name: 'jsp-api', version: '2.0'
```

**Comment by rkapsi** [comment]
I've just pushed a new build to maven central. It should fix this problem but there is a little API change. Please see the updated documentation and slightly changed Artifact ID.
